#---------------------------------------------
server:
  port: 1360
#---------------------------------------------
spring:
  application:
    name: oauth-service
  jpa:
    generate-ddl: true
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:mysql://192.168.1.10:3306/cloud?useUnicode=true&characterEncoding=UTF-8&useSSl=false&serverTimezone=GMT%2B8
    username: root
    password: xinyuan
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
      host: 192.168.1.14
      port: 5673
      username: admin
      password: 123456
#---------------------------------------------
eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.1.10:1300/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 3
    lease-expiration-duration-in-seconds: 10
#---------------------------------------------
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: ALWAYS
#---------------------------------------------

